## Literaturüberblick

Der Einfluss von Alter und Größe auf die Performance von Hedgefonds ist bereits Gegenstand vielfältiger Untersuchungen gewesen. @Stafylas.2016 gaben einen ersten Überblick über die bestehende Literatur. Die Autoren konstatierten, dass der überwiegende Teil bisheriger Studien eine negative Beziehung zwischen Alter und Performance feststellt. So untersuchte @Howell.2001 3.733 Hedgefonds im Zeitraum 1994-2000, wobei nur solche Hegdefonds als 'jung' eingestuft wurden, die ein Alter von bis zu drei Jahren aufwiesen. Der Autor ermittelte für das jüngste Dezil eine durchschnittliche Rendite von 21,5 % und für das älteste Dezil eine durchschnittliche Rendite von 11,8 % bei einer Median-Rendite von 13,9 % - eine Outperformance junger Hedgefonds von 760 Basispunkten.^[siehe @Howell.2001, S. 59]

@Amenc.2003 definierten ein Alter von bis zu zwei Jahren als 'jung' und berechneten auf Basis von 10 Modellen das Alpha für junge und alte Fonds. Neun Modelle ergaben hierbei signifikant höhere Alphas für junge Fonds - allerdings zum Preis einer ebenfalls höheren Volatilität.^[siehe @Amenc.2003, S. 22] @Frumkin.2009 hingegen untersuchten die Überrenditen von Hedgefonds im Vergleich zum S&P 500 im Zeitraum 2005-2007 unter Nutzung von drei Regressions-Modellen. Sie stellten fest, dass über alle Modelle hinweg das Alter einen signifikanten negativen Einfluss auf die Überrendite hat. Stieg das Alter um einen Monat, sank die Überrendite um bis zu 130 Basispunkten, wobei die Autoren dies auf einen sich mit der Zeit ändernden Investitionsstil der Fondsmanager zurückführten.^[siehe @Frumkin.2009, S. 249-250]

Zu einem ähnlichen Ergebnis kommt @Liang.1999, welcher durch eine Regression u.a. des Alters auf die durchschnittliche monatliche Rendite eine negative Beziehung zwischen Alter und Rendite feststellen konnte. Der Autor vermutet den Grund hierfür darin, dass mit dem Alter auch die Größe der Fonds wächst, und dadurch das Management derselbigen schwieriger werden könnte.^[siehe @Liang.1999, S. 78] @Jones.2007 analysierte in ihrer Studie einen Datensatz für den Zeitraum 01/1996-07/2006 und teilte die Fonds in jedem Monat in drei Altersklassen ein. Dadurch stellte sie fest, dass die Klasse der jungen Fonds eine durchschnittliche Rendite in Höhe von 17,5 % pro Jahr erwirtschaftete, im Vergleich zu 11,84 % pro Jahr in der Klasse der alten Fonds. Interessanterweise bieten junge Fonds mit einer jährlichen Standardabweichung von 5,97 % darüber hinaus eine geringere Volatilität als alte Fonds mit einer jährlichen Standardabweichung in Höhe von 6,32 %, was die Overperformance junger Fonds zusätzlich unterstreicht.^[siehe @Jones.2007, S. 347]

--> Paper über positive Beziehung?

Hinsichtlich der Beziehung zwischen Größe und Performance ist die Literatur jedoch uneinheitlich - positive wie negative Beziehungen wurden gleichermaßen wissenschaftlich festgestellt. Durch eine Querschnittsregression stellte beispielsweise @Liang.1999 einen positiven Zusammenhang für 385 Fonds zwischen 1994-1996 fest. Es handelt sich jedoch um einen kleinen Datensatz über einen kurzen Zeitraum, weshalb das Ergebnis kritisch betrachtet werden sollte.^[siehe @Liang.1999, S. 78] @Amenc.2003 untersuchten Hedgefonds im Zeitraum 1996-2002 und teilten diese nach Größe in zwei gleich große Gruppen ein. Wie bei der Untersuchung des Alters auch, wurde anschließend für jede Gruppe das durchschnittliche Alpha mit Hilfe mehrerer Modelle berechnet. Sieben dieser Modelle lieferten eine statistisch signifikante Overperformance von großen Fonds im Vergleich zu kleinen Fonds.^[siehe @Amenc.2003, S. 21] @Getmansky.2005 kam für den Zeitraum 1994-2002 zu einem ähnlichen Ergebnis, in dem sie eine positive, jedoch konkave, Beziehung zwischen Performance und historischer Größe für einen Datensatz von 3.501 Hedgefonds feststellen konnte.^[siehe @Getmansky.2005, S. 32]

@Koh.2003 konzentrierten sich auf asiatische Hedgefonds im Zeitraum 01/1999-03/2003 und teilten die betrachteten Fonds in zehn Kategorien nach Größe ein. Hierbei stellten sie für univariate Regressionen fest, dass Fonds, welche von großen Gesellschaften gemanagt wurden, solche Fonds outperformten, die von kleinen Gesellschaften verwaltet wurden. Dieser Effekt verschwand allerdings, wenn für weitere Variablen kontrolliert wird.^[siehe @Koh.2003, S. 21, 25, 39] Keinen statistisch signifikanten Zusammenhang zwischen Größe und Performance entdeckten hingegen @Gregoriou.2002 bei der Analyse einen Datensatzes von 276 Hedgefonds zwischen 1994-1999.^[siehe @Gregoriou.2002, S.76-77]

Wiederum andere Studien kommen zu der Schlussfolgerung, das zwischen Größe und Performance ein negativer Zusammenhang besteht. @Schneeweis.2002 untersuchten die Korrelation zwischen Größe und Performance für den Zeitraum 1996-2000. Hierbei entdeckten sie, dass große Fonds eine Underperformance im Vergleich zu kleinen Fonds aufwiesen. Eine mögliche Erklärung hierfür könnte die These sein, dass kleine Fonds riskantere Strategien nutzen.^[siehe @Schneeweis.2002, S. 19] @Agarwal.2004 betrachteten den Zeitraum 2004-2000 und entdeckten bei ihrer Analyse einen statistisch signifikanten negativen Zusammenhang zwischen Größe und Performance. Sie vermuten, dass es großen Fonds aufgrund ihrer Masse nicht mehr möglich ist, ihr gesamtes Kapital für die Top-Strategien einzusetzen.^[siehe @Agarwal.2004, S. 13, 25] Diese Vermutung hatten auch @Harri.2004, welche ebenfalls einen negativen Zusammenhang für den Zeitraum 1977-1998 feststellten.

Zu einem bemerkenswerten Ergebnis kam darüber hinaus @Hedges.2004, welcher den Zeitraum 1995-2002 betrachtete und hierfür drei Portfolios nach Größe zusammenstellte. Hierbei stellte der Autor zum einen eine Overperformance kleiner Fonds gegenüber großen Fonds fest, zum anderen jedoch auch eine gesamte Underperformance von Fonds in mittlerer Größe. @Ammann.2005 analysierten für ihre Studie 4.014 Fonds im Zeitraum 1994-2005, welche sie in 100 gleich große Portfolios aufteilten. Unter Nutzung eines Multi-asset-class Factor Models entdeckten sie einen negativen Zusammenhang zwischen Rendite und Fondsgröße. Die Autoren erklären sich diesen Zusammenhang dadurch, dass Fondsmanager durch Maximierung der Fondsgröße ihre Vergütung steigern können. Somit kommt es zur Überschreitung der optimalen Fondsgröße und daher bei zunehmender Größe zu abnehmender Performance.^[siehe @Ammann.2005, S. 236-237]

@Jones.2007 stellte für kleine Fonds eine jährliche Rendite von 15,46 % bei einer Standardabweichung von 6,31 % fest, sowie für große Fonds eine jährliche Rendite von 11,93 % bei einer Standardabweichung von 5,72 %. Insofern bieten kleine Fonds eine höhere Rendite, jedoch zum Preis einer höheren Volatilität.^[siehe @Jones.2007, S. 343] @Joenvaara.2012 betrachteten einen außergewöhnlich großen Datensatz mit insgesamt 30.040 Hedgefonds und berechneten für die Analyse Alphas auf Basis des Sieben-Faktoren-Modells von @Fung.2004. Sie errechnen ein jährliches Fung-und-Hsieh-Alpha von 6,47 % für kleine Fonds, sowie 1,67 % für große Fonds. Beide Ergebnisse sind statistisch signifikant und bestätigen den vermuteten negativen Zusammenhang.^[siehe @Joenvaara.2012, S. 20]

Somit lässt sich abschließend zusammenfassen, dass hinsichtlich der Auswirkungen des Alters auf die Performance die bisherige Literatur einhellig eine negative Beziehung festgestellt hat. Hinsichtlich des Zusammenhangs zwischen Größe und Performance ist sich die Literatur uneins, allerdings weist die Tendenz eher auf eine ebenfalls negative Beziehung hin.


## Herleitung der Hypothesen

Auf Basis der vorgestellten bisherigen Erkenntnisse der wissenschaftlichen Literatur, werden nachfolgend die zu untersuchenden Hypothesen abgeleitet. Da der weit überwiegende Teil der Literatur einen negativen Zusammenhang zwischen Alter und Performance bzw. Rendite von Hedgefonds festgestellt hat, wurde folgende erste Hypothese formuliert:
\begin{itemize}
  \item \(H_1:\) Junge Hedgefonds outperformen alte Hedgefonds.
\end{itemize}
Weiterhin zeichnet sich, trotz der Uneinigkeit in der Literatur, zuletzt eine Tendenz in Richtung eines negativen Zusammenhangs hinsichtlich Größe und Performance von Hedgefonds an. Dieser Richtung folgend, wurde folgende zweite Hypothese formuliert:
\begin{itemize}
  \item \(H_2:\) Kleine Hedgefonds outperformen große Hedgefonds.
\end{itemize}
Ob nun das Alter oder die Größe einen größeren Einfluss auf die Performance von Hedgefonds haben, wurde nach dem Wissen der Autoren in der Literatur bislang wenig untersucht. Da die Literatur zum Einfluss des Alters jedoch sehr eindeutig ausfällt, wird in der vorliegenden Arbeit die folgende dritte Hypothese untersucht:
\begin{itemize}
  \item \(H_3:\) Das Alter hat einen größeren Einfluss auf die Performance von Hedgefonds als deren Größe.
\end{itemize}

Nachdem nun die Hypothesen dargestellt wurden, erfolgt nachfolgend die Vorstellung des Datensatzes sowie die darauf angewendeten Methoden.