
## Robustness checks



- Durchführen der Regressionen mit Carhart's Alpha
- Durchführen der Regressionen mit dem Modell von Fung and Hsieh (1997)
- Logistic Regression der Charakteristika auf die Chance, oberhalb des Median (Winner) zu sein
- Einschränkung des Datensatzes auf bestimmte Strategien
  - HF Asia/Pacific Long/Short Equity
  - HF Bear Market Equity
  - HF Emerging Markets Long/Short Equity
  - HF Equity Market Neutral
  - HF Europe Long/Short Equity
  - HF Funds of Funds - Equity
  - HF Global Long/Short Equity
  - HF Long-Only Equity
  - HF U.S. Long/Short Equity
  - HF U.S. Small Cap Long/Short Equity
  

## Grenzen der Studie

Die Ergebnisse der vorliegenden Arbeit sind verschiedenen Grenzen und Kritikpunkten ausgesetzt. Zum einen enthielt der zur Verfügung stehende Datensatz die Größe der Hedgefonds zu lediglich einem Zeitpunkt und nicht fortwährend für jeden Monat. Diesen Ansatz verfolgten auch @Liang.1999 sowie @Gregoriou.2002b, was jedoch von @Ammann.2005 kritisiert wurde. Demnach könnte eine hohe Fondsgröße am Periodenende eher das Resultat guter vergangener Performance sein, sodass bei einem solchen Ansatz eher die Auswirkung der Performance auf die Größe und weniger die Auswirkung der Größe auf die Performance untersucht wird.^[siehe @Ammann.2005, S. 221] Des Weiteren wurde vorliegend ein vergleichsweise kleiner Datensatz analysiert, sowie die Aufteilung der Fonds in lediglich drei Klassen nach dem Vorbild von @Jones.2007 vorgenommen. Diese Aufteilung kritisieren @Ammann.2005 als nicht ausreichend, um valide Ergebnisse zu erhalten.^[siehe @Ammann.2005, S. 221] \newline
Da Hedgefonds auch Optionen sowie dynamische Trading-Strategien nutzen, führt dies zu einem eher nicht-linearen Exposure gegenüber üblichen Asset-Klassen [z.B. @Fung.1997], wodurch die Anwendung des CAPM zur Schätzung des Alpha zu verzerrten Ergebnissen führen könnte.^[siehe @Amenc.2003, S. 11] Da dies auch für die vorliegende Studie zutrifft, schränkt dies die externe Validität der Ergebnisse entsprechend ein. Stattdessen könnte das Alpha nach dem Multi-Faktor-Modell von @Fung.2004 berechnet werden, wie es bspw. @Joenvaara.2012 in ihrer Studie gemacht haben. \newline
Als letzten Punkt bezweifeln @Stafylas.2016 in ihrer Studie die Aussagekraft von Vergleichen zwischen Hedgefonds mit unterschiedlich langer Historie, welche ggf. sogar in unterschiedlichen Marktumgebungen ihre Tätigkeit gestartet haben. Die Ergebnisse solcher Vergleiche spiegeln wahrscheinlich nicht nicht die wahre Performance wieder.^[siehe @Stafylas.2016, S. 58] Um daraus resultierende "vintage effects" zu umgehen, haben beispielsweise @Schneeweis.2002 in ihrer Studie die Information Ratio nur für solche Hedgefonds berechnet, welche die gleiche Strategie haben sowie im selben Monat gestartet sind.^[siehe @Schneeweis.2002, S. 19] Dieser Ansatz wurde in der vorliegenden Studie nicht verfolgt, weshalb auch aus dieser Perspektive die externe Validität nur eingeschränkt gegeben ist.


\newpage