---
title: "Hedge Fund Performance and Fund Age and Size"
author1: "Luca"
adress_street_and_no1: "Königsworther Platz 1"
postcode1: "30167"
place1: "Hannover"
matriculation_number1: "1234567"
semester1: "1"
course_of_study1: "Wirtschaftswissenschaft"
# if you write in a team, put the data of the second author here:
author2: "Sebastian"
adress_street_and_no2: "Königsworther Platz 2"
postcode2: "30167"
place2: "Hannover"
matriculation_number2: "7654321"
semester2: "2"
course_of_study2: "Wirtschaftswissenschaft"
date: "31.03.2022"
university: "Leibniz University Hannover"
faculty: "School of Economics and Management" 
institute: "Institute of Banking and Finance"
advisor: "Prof. Dr. Maik Dierkes"
altadvisor: "Dr. Sebastian Schrön"
module: "Hedge Funds: Trading Strategies and Performance Evaluation"
# Belegnummer:
module_number: "374040"
lang: "de"
output: 
  pdf_document:
    template: ibf_template.tex
    extra_dependencies:
    - dcolumn
    toc: true
    toc_depth: 3
    highlight: tango
    keep_tex: false
    number_sections: true
geometry: "a4paper, left=2cm,right=5cm,top=3cm,bottom=3cm"
bibliography: BIB/bibliography.bib
csl: CSL/apa.csl
fontsize: 11pt
linestretch: 1.5
lof: true
lot: true
editor_options: 
  markdown: 
    wrap: sentence
---

```{r setup, include=FALSE, warning= FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

library(knitr)
library(tidyverse)
library(tinytex)

```

# Einleitung

```{r child='01_Einleitung.Rmd'}
```

# Theoretischer Hintergrund

```{r child='02_Theoretischer_Hintergrund.Rmd'}
```

# Datensatz und Methodik

```{r child='03_Datensatz_und_Methodik.Rmd'}
```

# Ergebnisse

```{r child='04_Ergebnisse.Rmd'}
```

# Robustheit und Grenzen der Studie

```{r child='05_Robustheit_und_Grenzen_der_Studie.Rmd'}
```

# Schlussfolgerung

```{r child='06_Schlussfolgerung.Rmd'}
```

<!-- this command \appendix changes the numbering of sections to alphabetical -->

```{=tex}
\appendix
\newpage
```
# Mitwirkung

```{r child='A1_Mitwirkung.Rmd'}
```

\newpage

# Tabellen

```{r child='A2_Tabellen.Rmd'}
```


<!-- Makes sure to have a new page for your literature -->


\newpage

# Literaturverzeichnis
